version: '3.9'

services:

  # PostgreSQL Database
  postgres:
    container_name: app_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passroot
      POSTGRES_DB: ebank
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  # Spring Boot Application
  app:
    container_name: app_main
    image: bank/app_main:1.0.0
    build: . # Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ebank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: passroot
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8085:8080"
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
volumes:
  postgres:
    driver: local