version: '3.9'

services:
  #new service (java_app)
  java_app:
    container_name: java_app
    image: ebank/java_app:1.0.0
    build: .
    ports:
      - 8085:8085
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/ebank #jdbc:postgresql://localhost:5432/E_BANK
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=passroot
    depends_on:
      - java_db

  #old service (postgres)
  java_db:
    container_name: java_db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passroot
      POSTGRES_DB: ebank
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}