spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ebank
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:test}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
server:
  port: ${SERVER_PORT:8085}
  error:
    include-path: always
    whitelabel:
      enabled: false

application:
  backend:
    basePath: http://localhost:8085
  frontend:
    basePath: http://localhost:4200
  security:
    jwt:
      secret-key: 586B633834416E396D7436753879382F423F4428482B4C6250655367566B5970
      expiration: 86400000
      cookie-name: jwt-cookie

cors:
  allowed-origins: "${application.frontend.basePath}"
  allowed-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
  allowed-headers: "Origin, Access-Control-Allow-Origin, Content-Type,
                         Accept, Jwt-Token, Authorization, Origin, Accept, X-Requested-With,
                         Access-Control-Request-Method, Access-Control-Request-Headers"
  exposed-headers: "Origin, Content-Type, Accept, Jwt-Token, Authorization,
                         Access-Control-Allow-Origin, Access-Control-Allow-Origin, Access-Control-Allow-Credentials"
  allow-credentials: true
  max-age: 3600
