# docker compose up -d --build
services:
  # PostgreSQL Database
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
      SERVICE_TAGS: prod
      SERVICE_NAME: postgresdb
    volumes:
      - postgres:/data/postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - postgresNetwork
    restart: unless-stopped
  # Spring Boot Application
  application:
    container_name: app_container
    image: ebanking:v1
    build: .. # Dockerfile
    depends_on:
      - postgres
    networks:
      - postgresNetwork
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ebank
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SERVICE_TAGS: prod
      SERVICE_NAME: bankApi
    ports:
      - "8085:8080"
    expose:
      - 8080
    restart: unless-stopped

networks:
  postgresNetwork:
    driver: bridge
volumes:
  postgres:
    driver: local
